var namespaceLEGS =
[
    [ "Abilities", "namespaceLEGS_1_1Abilities.html", "namespaceLEGS_1_1Abilities" ],
    [ "Characters", "namespaceLEGS_1_1Characters.html", "namespaceLEGS_1_1Characters" ],
    [ "Dialogue", "namespaceLEGS_1_1Dialogue.html", "namespaceLEGS_1_1Dialogue" ],
    [ "Inventory", "namespaceLEGS_1_1Inventory.html", "namespaceLEGS_1_1Inventory" ],
    [ "Items", "namespaceLEGS_1_1Items.html", "namespaceLEGS_1_1Items" ],
    [ "Quests", "namespaceLEGS_1_1Quests.html", "namespaceLEGS_1_1Quests" ],
    [ "Shop", "namespaceLEGS_1_1Shop.html", "namespaceLEGS_1_1Shop" ],
    [ "Tutorial", "namespaceLEGS_1_1Tutorial.html", "namespaceLEGS_1_1Tutorial" ],
    [ "ApplyForceOnCollision", "classLEGS_1_1ApplyForceOnCollision.html", null ],
    [ "Billboard", "classLEGS_1_1Billboard.html", null ],
    [ "Damageable", "classLEGS_1_1Damageable.html", "classLEGS_1_1Damageable" ],
    [ "DamageOverTimeStatusEffect", "classLEGS_1_1DamageOverTimeStatusEffect.html", "classLEGS_1_1DamageOverTimeStatusEffect" ],
    [ "DestroyAfterSeconds", "classLEGS_1_1DestroyAfterSeconds.html", null ],
    [ "DestroyOnCollision", "classLEGS_1_1DestroyOnCollision.html", null ],
    [ "Entity", "classLEGS_1_1Entity.html", "classLEGS_1_1Entity" ],
    [ "EntityDeathEventArgs", "classLEGS_1_1EntityDeathEventArgs.html", "classLEGS_1_1EntityDeathEventArgs" ],
    [ "EntityHealthChangeEventArgs", "classLEGS_1_1EntityHealthChangeEventArgs.html", "classLEGS_1_1EntityHealthChangeEventArgs" ],
    [ "EventDebugger", "classLEGS_1_1EventDebugger.html", null ],
    [ "EventManager", "classLEGS_1_1EventManager.html", "classLEGS_1_1EventManager" ],
    [ "Extensions", "classLEGS_1_1Extensions.html", null ],
    [ "IDamageable", "interfaceLEGS_1_1IDamageable.html", "interfaceLEGS_1_1IDamageable" ],
    [ "IEntity", "interfaceLEGS_1_1IEntity.html", "interfaceLEGS_1_1IEntity" ],
    [ "IStatusEffect", "interfaceLEGS_1_1IStatusEffect.html", "interfaceLEGS_1_1IStatusEffect" ],
    [ "IStatusEffectReceiver", "interfaceLEGS_1_1IStatusEffectReceiver.html", "interfaceLEGS_1_1IStatusEffectReceiver" ],
    [ "LEGEventArgs", "classLEGS_1_1LEGEventArgs.html", "classLEGS_1_1LEGEventArgs" ],
    [ "SpawnOnDestroy", "classLEGS_1_1SpawnOnDestroy.html", null ],
    [ "StatusEffect", "classLEGS_1_1StatusEffect.html", "classLEGS_1_1StatusEffect" ],
    [ "StatusEffectChangeArgs", "classLEGS_1_1StatusEffectChangeArgs.html", "classLEGS_1_1StatusEffectChangeArgs" ],
    [ "TimedStatusEffect", "classLEGS_1_1TimedStatusEffect.html", "classLEGS_1_1TimedStatusEffect" ],
    [ "TriggerApplyStatus", "classLEGS_1_1TriggerApplyStatus.html", "classLEGS_1_1TriggerApplyStatus" ]
];